kits:
  tools:
    name: TOOLS
    delay: 10
    items:
    - 272 1
    - 273 1
    - 274 1
    - 275 1
  dtools:
    delay: 600
    items:
    - 278 1 digging:1 durability:1 lootbonus:1 name:&4Gigadrill lore:The_drill_that_&npierces|the_heavens
    - 277 1 digspeed:3 name:Dwarf lore:Diggy|Diggy|Hole
    - 298 1 color:255,255,255 name:Top_Hat lore:Good_day,_Good_day
    - 279:780 1
  notch:
    name: Creator
    delay: 6000
    items:
    - 397:3 1 player:Notch
  color:
    delay: 6000
    items:
    - 387 1 title:&4Book_&9o_&6Colors author:KHobbits lore:Ingame_color_codes book:Colors
  firework:
    delay: 6000
    items:
    - 401 1 name:Angry_Creeper color:red fade:green type:creeper power:1
    - 401 1 name:StarryNight color:yellow,orange fade:blue type:star effect:trail,twinkle power:1
    - 401 2 name:SolarWind color:yellow,orange fade:red shape:large effect:twinkle color:yellow,orange fade:red shape:ball effect:trail color:red,purple fade:pink shape:star effect:trail power:1
holograms:
  holoid:
    text: "&aHello &bWorld"
    location: 0,10,0
    spawn: false
spawn:
  x: 0
  y: 100
  z: 0
  yaw: 0
  pitch: 0